name: Generate API reference via Doxygen and push to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Which git branch should I check out?'
        required: true
        default: 'master'           
      doc_version:
        description: 'Documentation version to generate'
        required: true
        default: '5.1.0'
      java_version:
        description: 'Java SDK version to use for documentation'
        required: true
        default: '5.1.0'


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.event.inputs.branch_name }}        
      DOC_VERSION: ${{ github.event.inputs.doc_version }}
      JAVA_VERSION: ${{ github.event.inputs.java_version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch_name }}
        fetch-depth: 0 # fetch all commits/branches for gitversion
       
    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    # Generate Java API reference 
    - name: Generate Documentation for Java
      run: |
        echo "PROJECT_NUMBER=${JAVA_VERSION}" >> doxygen/java-config
        mkdir -p "${BRANCH_NAME}/java/${JAVA_VERSION}"
        echo "OUTPUT_DIRECTORY=${BRANCH_NAME}/java/${JAVA_VERSION}" >> doxygen/java-config
        doxygen doxygen/java-config
    
     # Compresses HTML files into a tar.gz file
    - name: compress all API reference
      run: |
        tar -zcvf api_doc.tar.gz "${BRANCH_NAME}"
        ls -ll  

    - name: check if file exists
      run: |
        if [ -f api_doc.tar.gz ]; then
          echo "File exists"
        else
          echo "File does not exist"
          exit 1
        fi

