# Copyright (c) 2025 vesoft inc. All rights reserved.

name: release

on:
  release:
    types:
      - published

jobs:
  deploy-java:
    runs-on: [ self-hosted, linux ]
    steps:
      - name: Clean runner
        uses: webiny/action-post-run@3.1.0
        with:
          run: find . -mindepth 1 -delete

      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: install nebula
        run: |
          docker compose pull && docker compose up -d
          sleep 40
        working-directory: docker-compose

      - name: install nebula-ssl
        run: |
          docker compose pull && docker compose up -d
          sleep 40
        working-directory: docker-compose-ssl

#      - name: Deploy Release to Maven package
#        uses: samuelmeuli/action-maven-publish@v1
#        with:
#          gpg_private_key: ${{ secrets.JAVA_GPG_PRIVATE_KEY }}
#          gpg_passphrase: ""
#          nexus_username: ${{ secrets.OSSRH_USERNAME }}
#          nexus_password: ${{ secrets.OSSRH_TOKEN }}
#          maven_goals_phases: "clean deploy "

      - name: package client
        run: |
          mvn clean package

      - name: setup minio
        uses: vesoft-inc/.github/actions/setup-minio@master
        with:
          minio_url: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET }}

      - name: Get the version
        id: get_version
        run: |
          tag=$(echo ${{ github.ref }} | rev | cut -d/ -f1 | rev)
          tagnum=$(echo $tag | sed 's/^v//')
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "tagnum=$tagnum" >> $GITHUB_OUTPUT
        shell: bash

      - name: Copy java sdk to release on MinIO
        run: |
          mv target/ nebula-graph-java-sdk/
          tar czf ./nebula-graph-java-sdk-${{ steps.get_version.outputs.tagnum }}.tgz nebula-graph-java-sdk/driver-${{ steps.get_version.outputs.tagnum }}.jar
          sha256sum nebula-graph-java-sdk-${{ steps.get_version.outputs.tagnum }}.tgz > nebula-graph-java-sdk-${{ steps.get_version.outputs.tagnum }}.tgz.sha256sum.txt
          mc cp nebula-graph-java-sdk-${{ steps.get_version.outputs.tagnum }}.tgz minio/release-build/nebula-ng-java/${{ steps.get_version.outputs.tagnum }}/
          mc cp nebula-graph-java-sdk-${{ steps.get_version.outputs.tagnum }}.tgz.sha256sum.txt minio/release-build/nebula-ng-java/${{ steps.get_version.outputs.tagnum }}/
        working-directory: client

      - name: stop nebula
        if: always()
        run: |
          docker compose down
        working-directory: docker-compose

      - name: stop nebula-ssl
        if: always()
        run: |
          docker compose down
        working-directory: docker-compose-ssl
        
      - name: Trigger yueshu-release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GH_PAT }}
          repository: vesoft-inc/yueshu-release
          event-type: trigger-nebula-ng-java
          client-payload: '{"origin_tag": "${{ steps.get_version.outputs.tag }}"}'
